// FAQ backfill for existing blogs — the SAFE way.
//
// Instead of surgically editing the 215KB blogs.js (risky — one bad edit breaks
// the whole site build), this reads each blog, generates 4-6 standalone FAQs
// from its actual content via OpenAI, and writes them to a SEPARATE new file:
//   src/data/blogFaqs.js  ->  export const BLOG_FAQS = { "<slug>": [ {q,a} ] }
//
// blogs.js is NEVER modified. The patched BlogArticleSchema merges FAQs from
// blog.faqs (new posts) OR BLOG_FAQS[slug] (backfilled old posts). So every one
// of your existing 14 posts starts emitting FAQPage JSON-LD and becomes citable
// by AI engines — with zero risk to existing content.
//
// RUN (from the SITE repo root, with OPENAI_API_KEY in env):
//   OPENAI_API_KEY=sk-... node scripts/backfillFaqs.mjs
// It's idempotent: re-running only fills slugs not already in blogFaqs.js.

import { readFileSync, writeFileSync, existsSync } from 'fs';
import path from 'path';

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const MODEL = process.env.OPENAI_TEXT_MODEL || 'gpt-4o-mini';
const OUT = path.resolve('src/data/blogFaqs.js');

if (!OPENAI_API_KEY) { console.error('Set OPENAI_API_KEY'); process.exit(1); }

// Pull plain text out of a blog's sections for the LLM to read.
function blogText(blog) {
  const parts = [];
  for (const s of blog.sections || []) {
    if (s.type === 'h2' || s.type === 'p') parts.push(s.text || '');
    else if (s.type === 'p_with_link') parts.push(`${s.textBefore || ''} ${s.linkText || ''} ${s.textAfter || ''}`);
    else if (s.type === 'ul' && Array.isArray(s.text)) parts.push(s.text.join('. '));
  }
  return parts.join('\n').slice(0, 6000);
}

async function generateFaqs(blog) {
  const system =
    'You write FAQ pairs for a blog post, for FAQ schema (FAQPage JSON-LD). ' +
    'Produce 4-6 real questions a reader would ask, with concise STANDALONE answers ' +
    '(2-4 sentences) that make sense out of context. Base them ONLY on the post content. ' +
    'Do not invent statistics. Return STRICT JSON only: {"faqs":[{"q":"...","a":"..."}]}';
  const user = `Post title: ${blog.title}\nCategory: ${blog.category}\n\nContent:\n${blogText(blog)}`;

  const r = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${OPENAI_API_KEY}` },
    body: JSON.stringify({
      model: MODEL, temperature: 0.4,
      messages: [{ role: 'system', content: system }, { role: 'user', content: user }],
      response_format: { type: 'json_object' },
    }),
  });
  const d = await r.json();
  if (!r.ok) throw new Error(JSON.stringify(d?.error || d).slice(0, 200));
  const parsed = JSON.parse(d.choices[0].message.content);
  return Array.isArray(parsed.faqs) ? parsed.faqs : [];
}

// Load existing backfill (idempotent) by reading the current blogFaqs.js if present.
async function loadExisting() {
  if (!existsSync(OUT)) return {};
  try {
    const mod = await import(`file://${OUT}?t=${Date.now()}`);
    return mod.BLOG_FAQS || {};
  } catch { return {}; }
}

function writeOut(map) {
  const body =
    '// AUTO-GENERATED by scripts/backfillFaqs.mjs — FAQ data for existing blogs.\n' +
    '// Consumed by BlogArticleSchema to emit FAQPage JSON-LD. Safe to regenerate.\n' +
    '// blogs.js is intentionally NOT modified by the backfill.\n\n' +
    'export const BLOG_FAQS = ' + JSON.stringify(map, null, 2) + ';\n';
  writeFileSync(OUT, body, 'utf8');
}

async function main() {
  const { BLOGS } = await import('file://' + path.resolve('src/data/blogs.js'));
  const existing = await loadExisting();
  const map = { ...existing };
  let done = 0, skipped = 0;

  for (const blog of BLOGS) {
    if (map[blog.slug]?.length) { skipped++; continue; }
    process.stdout.write(`Generating FAQs: ${blog.slug} ... `);
    try {
      const faqs = await generateFaqs(blog);
      map[blog.slug] = faqs;
      writeOut(map); // write after each so a crash doesn't lose progress
      console.log(`ok (${faqs.length})`);
      done++;
    } catch (e) {
      console.log('FAILED:', e.message);
    }
  }
  console.log(`\nDone. Generated ${done}, skipped ${skipped} already-present. Wrote ${OUT}`);
  console.log('Next: git add src/data/blogFaqs.js && commit & push — Cloudflare redeploys, all posts emit FAQ schema.');
}

main().catch((e) => { console.error(e); process.exit(1); });
